name: CD
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  symfony-deploy:
    runs-on: self-hosted
    env:
      APP_ENV: prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up .env
      run: printf "DATABASE_URL=${{secrets.DATABASE_URL}}\nAPP_SECRET=${{secrets.APP_SECRET}}" > .env
    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Run migrations
      run: php bin/console doctrine:migrations:migrate
    - name: Copy files
      run: cp -r * /var/www/blog/ && cp .env /var/www/blog
